### ISSUE TITLE
Fails to get a simple object containing a string property

### ISSUE THREAD

**Issue by emilis-go** [dustinhayes/storage-native#1]
I tried reading/writing a simple object (`{test: 'abc'}`) from/to SessionStorage.

Getting the object failed with an exception:

> Uncaught SyntaxError: Unexpected token a(…)
> (anonymous function) @ parse.js:15
> module.exports @ parse.js:10
> getItem @ store.js:11

May be a bug in _json-native_, may be a bug in how you are using it.

**Comment by dustinhayes** [comment]
Sorry for the super delayed response. I found the issue and fixed it with the latest version
